name: webunicamp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  cloud_firestore: ^5.5.0
  image_network: ^2.5.6
  carousel_slider: ^5.0.0
  latlng: ^2.0.7
  flutter_map: ^7.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/roxas.jpg
   - assets/addu_logo.png
   - assets/aerial.jpg
   - assets/addu.png
   - assets/mainpage.png
   - .env
  fonts:
    - family: Trajan
      fonts:
        - asset: assets/fonts/Trajan.ttf
